wanted-group-4/wanted-preonboarding-tripbtoz

src/routes/Router.tsx
- router 오타 수정
- Router 컴포넌트에 import 오타 수정
=> style: router 오타 수정

package.json, src/App.tsx, src/api/index.ts, src/api/searchApi.ts, yarn.lock
- 호텔 리스트를 갖오고는 getHotels 함수 작성
- 무한스크롤을 생각해서 page 값을 인자로 받음
- 호텔 하나의 정보를 갖고오는 getHotelInformation 함수 작성
- 해당 컴포넌트에서 api를 import 해와서 변수에 선언하고 사용
```javascript
import {getHotels, getHotelInformation} from '@api/searchApi';
const test1 = getHotels(1); // 처음 10개의 호텔 리스트가 나옴
console.log(test1.data);
const test1 = getHotels(2); // 그다음 10개의 호텔 리스트가 나옴
const test2 = getHotelInformation('Bucheon A Plus')
console.log(test2.data);
```
=> feat: 호텔 리스트 get api, 호텔 하나 get api

src/components/modal/ConfirmReservation.tsx, src/components/modal/GuestReservation.tsx
UI 완성
서치바 - 인원 선택 모달,
서치바 - 예약 확인 모달
src-components-modal폴더를 만들어 그 안에서 작업했습니다. 
components폴더에 common폴더를 만들어 그 안에 modal폴더를 만드는게
좋을까요?
=> feat: 인원선택, 예약확인 모달 UI

package.json, src/components/calendar/Calendar.tsx, src/components/calendar/Dates.tsx, src/components/calendar/Month.tsx, src/components/calendar/Week.tsx, src/components/calendar/index.ts, src/constants/day.ts, src/utils/disabledDate.ts, src/utils/setDefaultDate.ts, yarn.lock
resolved #12 
Calendar 컴포넌트 구현 
- 캘린더 현재월부터 1년 치 월 표시
- 날짜 클릭시 checkIn
- 두번째 클릭시 값에따라 checkIn/checkOut
=> feat: Calendar 컴포넌트 구현 

src/components/hotel/HotelCard.tsx, src/components/hotel/ReserveCard.tsx, src/components/hotel/index.ts, src/pages/Detail.tsx
상세페이지 구현
상세 페이지 구현 (현재 data가 연결이 안되어있어 Dummy data를 사용하여 구현)
=> feat: 상세페이지 구현 (Dummy data)

src/components/search/SearchBar.tsx, src/hooks/useIntersection.ts, src/pages/Search.tsx, yarn.lock
Landing page & 무한스크롤 구현
무한스크롤 customhook 구현
hook 
```js
function useIntersection({
root, // 교차여부 확인할때 기준이 되는 요소 ( visual view port 가 아닌 layout view port 기준 )
rootMargin = '0px', // css와 마찬가지로 root의 margin 값
threshold = 1, // 타겟 요소의 가시성여부 판단값 0~1
//위 세가지 옵션은 넣어줘도되고 안넣어줘도 됩니다 
onIntersect, // 타겟 요소가 교차될때 실행할 함수
}: Props) {
const [target, setTarget] = useState<HTMLElement | null | undefined>(null);
useEffect(() => {
if (!target) return; // target 이 없을경우 실행 x 
const observer: IntersectionObserver = new IntersectionObserver( //api 인스턴스 생성
onIntersect, //타겟 요소가 교차될때 실행할 함수
{ root, rootMargin, threshold },
);
observer.disconnect(); //인스턴스가 관찰하고있던 모든 요소들의 관찰 중지
observer.observe(target); // target 관찰 시작
return () => observer.unobserve(target); // cleanup - target 관찰중지 ( disconnect: 모든 관찰 중지 / …
```
=> feat: Landing page & 무한스크롤 구현

src/components/calendar/Calendar.tsx, src/components/calendar/CalendarHeader.tsx, src/components/calendar/CalendarModal.tsx, src/components/calendar/Month.tsx, src/components/search/SearchBar.tsx, src/components/search/SearchCount.tsx, src/components/search/SearchDate.tsx, src/types/search.ts, src/utils/getDate.ts, src/utils/setDefaultDate.ts
- resovled #27 
- SearchBar에 modal display / data sate 생성
- 캘린더와 인원체크 modal을 display관련 state 생성
- 캘린더와 인원체크의 date 관련 state 생성
- modal의 state변경을 위한 함수생성
-  CalendarModal에 SearchBar에 생성된 state 적용
- 현재 날짜를 얻을수있는 getDate 함수생성
=> feat: SearchBar mdoal display/ data관련 state 생성 및 변경

src/components/modal/ConfirmReservation.tsx, src/components/modal/GuestReservation.tsx, src/components/modal/MobileHeader.tsx, src/components/search/SearchBar.tsx
인원 체크 모달 기능 완성
- 인원 체크 모달 기능 구현
- 반응형 css
- 서치바에 연결
- MobileHeader 생성 ( GuestReservation 이 태블릿,모바일로 바뀔 경우 생성되는 컴포넌트 )
=> feat: 인원체크 모달 (#31)

src/components/hotel/HotelCard.tsx, src/components/layout/Header.tsx, src/components/layout/Layout.tsx, src/pages/Detail.tsx, src/pages/Search.tsx
피그마 디자인에 맞게 호텔 카드, 상세페이지 반응형 구현
호텔 카드, 상세페이지 반응형 구현
=> design: 호텔 카드, 상세페이지 반응형 구현 (#33)

src/api/reserveApi.ts, src/api/searchApi.ts
- 예약 api 구현
- fetchHotels 리팩토링
- useInfiniteQuery의 두번째 인자에 fetchHotels 넣기
- useQuery는 더이상 안쓰임
- 예약 api 사용 방법
```javascript
import {patchReserveHotel} from '@api/reserveApi';
const test1 = patchReserveHotel();
const handleOnclick = () => {
const name = 호텔이름; // string
const check_in = 시작날짜; // any
const check_out = 마지막날짜; // any
const adult = 숫자; // number
const child = 숫자; // number
const occupancy = {adult, child};
test1.mutate({name, check_in, check_out, occupancy});
}
```
=> feat: 예약 api 구현하기

src/components/search/SearchBar.tsx
오타수정 , 최상단 태그에 position:relative 추가
=> design: position추가 및 오타수정

src/api/searchApi.ts
- react-query, useInfiniteQuery 에 맞게 리팩토링
- response -> response.data
- useQuery 제외 -> useInfiniteQuery에 들어가는 fetch 함수로 리팩토링
=> refactor: react-query 사용성 개선

src/components/search/SearchCount.tsx
=> debug: 오타로 인한 서치바 깨짐  수정

src/api/searchApi.ts
- 무한스크롤 요청 시 setTimeout 설정
```javascript
const getDelay = (delay: number) =>
new Promise(resolve => setTimeout(resolve, delay));
await getDelay(500);
```
=> feat: 무한스크롤 요청 시 setTimeout 설정 (#42)

src/components/hotel/HotelCard.tsx, src/pages/Search.tsx
Search 페이지의 호텔 카드 컴포넌트 로드 시 fade in 되도록 애니메이션 구현
Search 페이지 호텔 카드 fade in 애니메이션 추가
=> design: Search 페이지 호텔 카드 fade in 애니메이션 추가

src/components/modal/GuestReservation.tsx
=> refactor: 함수 수정 및 인원 디폴트값 변경

src/api/reserveApi.ts
- 예약된 호텔 리스트 갖고오는 get api
- useInifiniteQuery 사용을 염두에 두고 작성
=> feat: 예약된 호텔 get api

src/components/common/skeleton/HotelCardSkeleton.tsx, src/pages/Search.tsx
사용자 경험을 높이기 위해 Search 페이지의 무한스크롤 skeleton loader 추가
Search 페이지 hotel card에 skeleton loader 추가
=> design: Search 페이지 무한스크롤 skeleton loader 추가 (#53)

src/components/calendar/Calendar.tsx, src/components/calendar/CalendarModal.tsx, src/components/calendar/Dates.tsx, src/components/layout/Header.tsx, src/components/search/SearchBar.tsx, src/constants/day.ts, src/hooks/useLocationString.ts, src/utils/setDefaultDate.ts
- handleSearch 함수 적용 및 width변동에 따른 scorll 제어
- resolved #59
- CalendarModal에 적용버튼에 handleSearch 함수 적용
- 랜딩페이지에 layout header fixed 추가
-  search date default value를 location hook으로 이동
- width변경시 scroll제어
- search 실행시 modal 닫힘
=> feat: handleSearch 함수 적용 및 width변동에 따른 scorll 제어

src/api/searchApi.ts
- 호텔 get api 리팩토링
```javascript
export const fetchHotels = async ({ pageParam = 1, queryKey }) => {
const maxPerson = queryKey[1];
try {
if (maxPerson) {
const response = await axios.get(
`${BASE_URL}/hotels?occupancy.max_gte=${maxPerson}&_sort=occupancy.max&_page=${pageParam}`,
);
await getDelay(500);
return response.data;
} else {
const response = await axios.get(
`${BASE_URL}/hotels?_page=${pageParam}&_limit=10`,
);
await getDelay(500);
return response.data;
}
} catch (error) {
console.log(error);
}
};
```
=> refactor : 호텔 get api 리팩토링

src/pages/Search.tsx
[소희님이 구현해주신 기능을 적용 했습니다](https://github.com/wanted-group-4/wanted-preonboarding-tripbtoz/pull/40)
=> feat: 검색 결과와 함께 detail 페이지로 이동 구현

src/components/search/SearchBar.tsx
- 서치 버튼 position, z-index 적용해서 
- 모달창을 나가지 않고도 검색 가능하도록 구현
=> design: 서치 버튼 position, z-index 적용

src/components/hotel/HotelCard.tsx
트립비토즈 fade-in animation 속성과 똑같게 수정
design: 호텔 카드 fade in 애니메이션 속성 변경
=> design: 호텔 카드 fade in 애니메이션 속성 변경

src/components/layout/Header.tsx, src/pages/Search.tsx
search-page ui 수정
- 검색결과 호텔이 없으면 스켈레톤 ui , 마지막호텔입니다 계속 보이는 현상 수정
- 호텔 카드 width tablet 기준 크기변경 
- 랜딩페이지에서 고정
=> fix: search-page ui 수정

src/components/hotel/ReserveCard.tsx, src/hooks/useLocationString.ts, src/pages/Detail.tsx
호텔 예약 시 호텔 정보 저장 
호텔 예약 버튼 클릭 시 호텔이름을 key 값으로 호텔 정보를 localstorage에 저장
=> feat: 호텔 예약 버튼 기능 구현 (#64)

src/components/modal/GuestReservation.tsx
refactor: pathname에 따른 인원체크 모달 위치선정
=> refactor: pathname에 따른 인원체크 모달 위치선정

src/components/calendar/CalendarModal.tsx, src/components/search/SearchBar.tsx
SearchBar 페이지별 fixed 적용
- SearchBar에 fixed를 홈일때만 적용
- Modal에도 페이지별 위치지정
=> refactor: SearchBar 페이지별 fixed 적용

src/api/reserveApi.ts
- name으로 되있던 변수명 hotelName으로 수정
=> refactor: hotelName으로 변수 이름 수정

src/hooks/useLocationString.ts, src/pages/Detail.tsx
detail 페이지 기존 dummy 데이터 제거 후 실제 데이터 추가
detail 페이지 hotel fetch api 추가
스켈레톤 loader 추가
=>  feat: detail 페이지 hotel fetch api 추가

src/api/reserveApi.ts, src/pages/Detail.tsx
detail 페이지 reserve patch api 추가
detail 페이지 reserve patch api 추가
=> feat: detail 페이지 reserve patch api 추가

src/components/modal/ConfirmReservation.tsx, src/components/modal/GuestReservation.tsx, src/routes/Router.tsx
- 확인모달 반응형 추가  
- 인원체크 모달 반응형 수정
=> refactor: 확인 모달 ,  인원체크 모달 반응형 

src/components/calendar/CalendarModal.tsx, src/components/search/SearchBar.tsx
- handleSearch 변경
- calendar modal css 변경
- handleSearch에 overflow hidden 제거 추가
- calendar modal css top 수정
- search icon 위치변경
=> refactor: search 및 calendar modal 변경 

src/pages/Detail.tsx
detail 페이지 searchbar 추가
detail 페이지 searchbar 추가
=> feat: detail 페이지 searchbar 추가

src/components/hotel/HotelCard.tsx
호텔 카드 컴포넌트 base, max 타입 수정
호텔 카드 컴포넌트 base, max 타입 수정
=> fix: 호텔 카드 컴포넌트 base, max 타입 수정

src/routes/Router.tsx
=> refactor: 라우터 수정

src/pages/MyPage.tsx, src/pages/Search.tsx
=> feat: mypage 구현

src/components/calendar/CalendarModal.tsx, src/components/search/SearchBar.tsx
search css 수정
- searchBar width 수정
- searchIcon 수정
=> design: search css 수정

src/api/reserveApi.ts, src/pages/Detail.tsx
=> refactor: 호텔 예약 api에 interface 추가

src/components/search/SearchBar.tsx
- search icon 수정
- 
- 조건부렌더링 대신 css media 를 사용한 display로 변경
=> design: serach icon css 수정
